[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"

[project]
name = "nix_analyzer"
version = "0.1.0"
authors = [{ name = "Your Name", email = "your@email.com" }]
description = "A Nix expression analyzer with a Rust-powered parser"
license = "MIT"
dependencies = []
